### ISSUE TITLE
Can you pass param from one task to another

### ISSUE THREAD

**Issue by popomore** [robrich/orchestrator#12]
```
var Orchestrator = require('orchestrator');
var orchestrator = new Orchestrator();

orchestrator.add('task_a', function() {
  return 'a';
});

orchestrator.add('task_b', function(callback) {
  callback(null, 'b');
});

orchestrator.add('task_c', ['task_a', 'task_b'], function(callback, results) {
  // results is ['a', 'b']
});
```

**Comment by andrew-aladev** [comment]
```
gulp.task("a", function(callback) {
    callback(null, 1);
});
gulp.task("default", ["a"], function (callback) {
    console.log(arguments);
});
```

The result is `{ 0 : function (err) { finish(err, 'callback'); } }`. There are no results available. The author of this "orchestrator" advises to use variable from parent scope to share these results. Please stop the planet - I'm going out.

![facepalm](http://i.imgur.com/prmVSf7.gif)

**Comment by bcherny** [comment]
:+1: this is a very common use case, especially with gulp-

```js
gulp.task('allJs', () => {
  gulp
    .src('js/*.js')
    ...
})
gulp.watch('js/*.js', ['allJs'])
```

the above will rebuild all js every time one file is modified. the typical advice is to add gulp-remember and gulp-cached to the mix, but they will slow the build for the watch down proportionally to the size of the build (for me, building a single file takes 10ms, but building the same file without concating, using cached and remember takes 2s).

how could we make the `allJs` task generic enough to be called with any number of files?

we could extract the body of the `allJs` task into its own function, and call tha function from both the `allJs` task and the `watch` task; but this would not work when `allJs` has a dependency. i have yet to find a clean workaround :(

**Comment by loficode** [comment]
Why not do it like this and just target the file that triggered the watch

```javascript
gulp.task('allJs', () => {
  gulp.watch('js/*.js', (e) => {
    gulp.src(e.path, {'base': 'js/'})
      ...
  });
})
```
