### ISSUE TITLE
Why orchestrator is Max concurrency ?

### ISSUE THREAD

**Issue by whps** [robrich/orchestrator#76]
As I konw Js is single thread. 
I saw sequencify in package.json, that just anlysis dep and do them.
Is that means if a task is CPU type task, is not real concurrency. But I/O or other Async task is real.
I thought U new a process.child implement the real concurrency, but not.

**Comment by robrich** [comment]
JavaScript is single threaded, but Node's event loop allows many threads to
be in flight at once. Periodically the event loop checks back with each
waiting I/O task to see if it's done yet, and if so, continues on with this
thread, pausing all the others. This max concurrency setting controls how
many of these threads we stack up at once. Too many threads and the event
loop takes a long time to get back to each request, too few and the CPU is
idle waiting for any of the I/O tasks to finish.
